### ISSUE TITLE
`browser.newtabpage.enabled` set to `false` prevents the URL bar from being focused

### ISSUE THREAD

**Issue by aplaice** [andreicristianpetcu/Search-and-Switch-Containers#7]
### To reproduce: 

1. In `about:config` set `browser.newtabpage.enabled` to `false`.
2. Open a new tab (e.g. with `Ctrl-t`)
3. Switch containers (e.g. type `co Personal` and press enter).

### Expected result:

The container of the new tab is changed to `Personal` (in the example given) and the URL bar/omnibox is kept focused (with the cursor inside).

### Actual result:

The container of the new tab is changed to `Personal`, but the URL bar/omnibox loses focus. (This is obviously not a gigantic problem, as focus can be regained with `Ctrl-l`, but it's slightly annoying.)

### Further details:

The bug occurs with both Firefox 60 and nightly. I think I have located the source of the problem and will send a pull request shortly.

PS I love your extension and now almost can't imagine life/Firefox without it. It's one of the main reasons why I think that the transition to Webextensions isn't *that* terrible. :)

**Comment by andreicristianpetcu** [comment]
Thank you! Sorry I did not see this before :)

**Comment by aplaice** [comment]
Don't worry! Thanks for merging!

**Comment by andreicristianpetcu** [comment]
@aplaice Sorry for this huge delay but your patch landed in AMO just now. I simply did not have time to test it until now. Sorry. You can force an update to get it from the gear icon in about:addons.

**Comment by aplaice** [comment]
Thanks for testing, pushing it to AMO and for the heads up! (As well as, again, for making this in the first place!)

Also, really please don't worry! (FWIW I had been temporarily running a modified, unlisted version of the addon, but I'm happy to be back to the mothership. :))
